# 📘 Modul Praktikum: Pengenalan NumPy untuk Statistik Deskriptif 

**Level:** Pemula — mulai dari dasar


## 🎯 Tujuan Pembelajaran
Setelah menyelesaikan modul ini mahasiswa dapat:

1. Menjelaskan apa itu NumPy dan keunggulannya dibanding list Python.
2. Membuat array 1D dan 2D dengan berbagai metode.
3. Mengakses, slicing, dan memanipulasi array (satu perintah per cell).
4. Menghitung ukuran tendensi sentral (mean, median, mode) dan ukuran variasi (var, std, range, IQR).
5. Mengerjakan latihan praktis di cell yang disediakan.

## 📘 Bagian A — Persiapan
Jalankan cell berikut untuk mengimpor library yang diperlukan.

> Catatan: jika belum menginstall SciPy, jalankan `pip install scipy` di terminal atau environment Anda.

In [2]:
import numpy as np

**NumPy** adalah library untuk bahasa pemrograman Python yang berguna untuk menambahkan dukungan yaitu array dan matriks multi-dimensi yang besar, bersama dengan koleksi fungsi matematika tingkat tinggi untuk beroperasi pada array.

In [3]:
from scipy import stats

In [4]:
print('NumPy versi:', np.__version__)

NumPy versi: 1.24.3


### 1. Membuat numpy array

Untuk membuat sebuah array numpy dapat melakukannya dengan casting dari list menjadi array dengan menggunakan fungsi **array()**.

In [5]:
arr = np.array([1, 2, 3, 4, 5])

In [6]:
arr

array([1, 2, 3, 4, 5])

Untuk memeriksa tipe variabel yang telah di inisialisasi sebelumnya dapat menggunakan fungsi **type()**, jika telah berhasil menginisialisasi array maka outputnya akan menampilkan hasil yang sama dengan output dari baris code dibawah.

In [7]:
# Memperiksa type

type(arr)

numpy.ndarray

### 2. Membuat array dengan `arange` (mirip range)
Contoh: mulai 0 sampai 8 langkah 2.

In [9]:
arr_arange = np.arange(0, 10, 2)

In [10]:
arr_arange

array([0, 2, 4, 6, 8])

### 3. Membuat array dengan `linspace` (nilai terdistribusi merata)
Contoh: 5 nilai antara 0 dan 1.

In [11]:
arr_linspace = np.linspace(0, 1, 5)

In [12]:
arr_linspace

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### 4. `zeros` dan `ones`

In [13]:
np.zeros(4)

array([0., 0., 0., 0.])

In [14]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

### 5. Membuat data random untuk data dummy

Fungsi ini digunakan untuk mengatur “benih” (seed) dari generator bilangan acak di NumPy.
Tujuannya: agar hasil bilangan acak yang dihasilkan selalu sama setiap kali program dijalankan.
Nilai seed — yaitu angka awal yang menentukan urutan bilangan acak yang akan dihasilkan.

In [17]:
np.random.seed(0)

np.random.randint(low, high, size)

In [16]:
np.random.randint(1, 100, size=6)

array([45, 48, 65, 68, 68, 10])

Setiap nilai seed yang berbeda akan menghasilkan urutan angka acak yang berbeda.
Tapi jika kamu gunakan seed yang sama, hasilnya akan selalu sama, meskipun dijalankan berkali-kali.

### 6. Tipe data (`dtype`) dan dimensi (`shape`, `ndim`)

In [18]:
a = np.array([1, 2, 3])

In [19]:
b = np.array([1.0, 2.0, 3.0])

In [20]:
a.dtype, a.shape

(dtype('int32'), (3,))

In [21]:
b.dtype, b.shape

(dtype('float64'), (3,))

In [22]:
c = np.array([[1,2,3],[4,5,6]])

In [23]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
c.shape, c.ndim

((2, 3), 2)

### 7. Indexing & Slicing — contoh sederhana

In [25]:
arr = np.arange(10)

In [26]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr[2]

2

In [28]:
arr[2:7]

array([2, 3, 4, 5, 6])

In [29]:
arr[:5]

array([0, 1, 2, 3, 4])

In [30]:
arr[arr % 2 == 0]  # boolean indexing

array([0, 2, 4, 6, 8])

## 📊 Bagian B — Statistik Deskriptif (Langkah-per-Langkah)
Gunakan `data` berikut untuk setiap contoh:

In [31]:
data = np.array([10, 12, 15, 18, 20, 22, 25, 30, 30])

In [32]:
data

array([10, 12, 15, 18, 20, 22, 25, 30, 30])

### Mean (rata-rata) — gunakan `np.mean()`

In [33]:
mean_value = np.mean(data)

In [34]:
mean_value

20.22222222222222

### Median — gunakan `np.median()`

In [35]:
median_value = np.median(data)

In [36]:
median_value

20.0

### Modus — gunakan `stats.mode()` dari SciPy

In [37]:
mode_result = stats.mode(data, keepdims=True)

In [38]:
mode_result

ModeResult(mode=array([30]), count=array([2]))

In [39]:
mode_result.mode[0]  # nilai modus

30

### Varians dan Standar Deviasi
- `np.var()` population variance
- `np.std()` population std
Untuk sample variance/std gunakan `ddof=1`.

In [40]:
var_pop = np.var(data)

In [41]:
std_pop = np.std(data)

In [42]:
var_sample = np.var(data, ddof=1)

In [43]:
std_sample = np.std(data, ddof=1)

In [44]:
var_pop, std_pop, var_sample, std_sample

(46.839506172839506, 6.8439393753042195, 52.69444444444444, 7.259093913460855)

### Range dan IQR
Range = max - min. IQR = Q3 - Q1 (gunakan `np.percentile`).

In [45]:
range_value = np.max(data) - np.min(data)

In [46]:
Q1 = np.percentile(data, 25)

In [47]:
Q3 = np.percentile(data, 75)

In [48]:
range_value, Q1, Q3, Q3 - Q1

(20, 15.0, 25.0, 10.0)

## 📋 Bagian C — Latihan Praktik (Isi pada cell yang disediakan)
Instruksi langkah-per-langkah: buat array `nilai_mahasiswa` 15 elemen, cetak shape & dtype, lalu hitung semua ukuran statistik yang dipelajari.

**Instruksi detail (ikuti setiap baris dan isi pada cell kode di bawahnya):**
1. Buat array `nilai_mahasiswa` dengan 15 nilai (misal: 65,70,...)
2. Cetak `nilai_mahasiswa.shape`
3. Cetak `nilai_mahasiswa.dtype`
4. Hitung `np.mean(nilai_mahasiswa)`
5. Hitung `np.median(nilai_mahasiswa)`
6. Hitung modus dengan `stats.mode(nilai_mahasiswa)`
7. Hitung varians sample dengan `np.var(..., ddof=1)`
8. Hitung std sample dengan `np.std(..., ddof=1)`
9. Hitung range dan IQR.

In [ ]:
# ====== CELL LATIHAN: ISI DI SINI ======
# 1. Buat array nilai_mahasiswa (15 elemen)
nilai_mahasiswa = np.array([65, 70, 72, 68, 90, 85, 77, 60, 55, 78, 82, 69, 74, 88, 91])

# 2. Cetak shape
nilai_mahasiswa.shape

In [ ]:
nilai_mahasiswa.dtype

In [ ]:
np.mean(nilai_mahasiswa)

In [ ]:
np.median(nilai_mahasiswa)

In [ ]:
stats.mode(nilai_mahasiswa, keepdims=True)

In [ ]:
np.var(nilai_mahasiswa, ddof=1)

In [ ]:
np.std(nilai_mahasiswa, ddof=1)

In [ ]:
np.max(nilai_mahasiswa) - np.min(nilai_mahasiswa)

In [ ]:
np.percentile(nilai_mahasiswa, 25), np.percentile(nilai_mahasiswa, 75), np.percentile(nilai_mahasiswa,75)-np.percentile(nilai_mahasiswa,25)

## 🧪 Latihan Tambahan: Data Dummy (Distribusi Normal)
Buat `tinggi_badan` distribusi normal (mean=165, sd=8, size=30) dan hitung statistik dasar.

In [ ]:
np.random.seed(1)

In [ ]:
tinggi_badan = np.random.normal(loc=165, scale=8, size=30)

In [ ]:
np.mean(tinggi_badan)

In [ ]:
np.median(tinggi_badan)

In [ ]:
np.std(tinggi_badan, ddof=1)

In [ ]:
np.var(tinggi_badan, ddof=1)

In [ ]:
np.max(tinggi_badan) - np.min(tinggi_badan)

In [ ]:
np.percentile(tinggi_badan,25), np.percentile(tinggi_badan,75), np.percentile(tinggi_badan,75)-np.percentile(tinggi_badan,25)

## 📚 Tugas Mandiri
1. Buat laporan singkat yang membandingkan `nilai_mahasiswa` dan `tinggi_badan`.
2. Jelaskan perbedaan population vs sample variance dan kapan menggunakan `ddof=1`.